### ISSUE TITLE
Santa Barbara amlr07-20240907 deployment

### ISSUE THREAD

**Issue by acossio** [us-amlr/glider-lab#24]
Checklist for ESD glider deployment todo tasks. Note that file paths are relative to the top-level glider folder (i.e. glider-YYYYYmmdd)

# Before deployment

## Glider Build
- [x] Determine what batteries will be used for the mission (Lithium primary or rechargeable) and install. This includes a new emergency battery. Write installation date on the primary batteries. Make sure the correct amphrs are in autoexec.mi (f_coulomb_battery_capacity). If using used primary batteries, make sure that the amphrs are set by typing put m_coulomb_amphr_total (used amphrs).
- [x] Ballast the glider for the condtions that it will be deplyed in. [TWR ballast sheet](https://datahost.webbresearch.com/download/file.php?id=91) or [Rutgers ballast sheet](https://docs.google.com/spreadsheets/d/1BrgEZyT4qzZ22Rkcxc7ZHFRZ-m1zfW3o/edit?usp=sharing&ouid=102683297276185841842&rtpof=true&sd=true)
- [ ] Optional. Check pump range while in the ballast tank if the glider hasn't been used in a while.
- [x] Make sure the glider has the most recent operating system. [Datahost website](https://datahost.webbresearch.com/files.php?cwd=/glider)
- [x] Final Seal. Replace all the hull seals and O-rings for sensors that need replacing. Note the internal and external weight distribution on the Ballast Sheet. As you seal the glider at each section, take photos of the connections.
- [x] After Final Seal, recheck the ballast and that the roll is less than 5 degrees.
- [x] Perform a Functional Checkout Procedure. Also download the longterm.sta when downloading the files that the Functional Checkout states. 
- [ ] Check on [Argos website](https://argos-system.clsamerica.com/argos-cwi2/login.html) that the glider Argos test worked during the Functional Checkout Procedure.
- [ ] If possible, in the tech tank, perform the missions od5.mi and 1k_n.mi using mission and sensor parameters. Make sure the glider looks like it is diving close to correctly and that all the sensors are working and collecting data. All sensor output should be seen including .ad2, .azf, .cam when applicable. 
- [ ] Make sure that the serial numbers are correct in autoexec.mi and proglets.dat and update [Fleet Status](https://docs.google.com/spreadsheets/d/1tB3QNKYx8qOYYS9QZotekBAx0y-_n2d-EZPjFFdYNuU/edit?gid=0#gid=0)
- [ ] Optional. Perform a compass calibration if necessary. [SOP](https://docs.google.com/document/d/1Ny_K8jxSWA71vFyzvtJ7bK2i5aDPo2gu/edit?usp=sharing&ouid=102683297276185841842&rtpof=true&sd=true)
- [x] Calibrate Shadowgraph if installed. Then clear the memory if there were photos on it.
- [ ] Calibrate acoustics (AZFP or Nortek mini) if installed. Then clear the memory if data is on it.
## Glider Planning
- [ ] Planner provide, in one location, written sensor settings. [Settings and Sampling Document](https://docs.google.com/spreadsheets/d/1SNjvXY9RhGC8St3bXdfQx6tWN10sF8evctD0B_RcTKk/edit?gid=0#gid=0)
- [ ] Load all files and settings on the glider and attached sensors (ie Shadowgraph, AZFP, Nortek).
- [ ] If possible, verify sensor settings for camera, azfp, and/or Nortek. Either through a test file or some sensor dependent way. (ie silhouetteConfig.txt for camera, Getall comand for Nortek)
- [ ] Put files on the SFMC to be loaded on the glider just before deployment. (mission and mission related (ma files), sensor cfg and ini, and sample files.

## Data Prep
- [ ] Download the [GDrive folder template](https://drive.google.com/drive/folders/1xBYTSP8GOHA35bxVoqH7czrJn4ekYrjI?usp=drive_link) and rename it (glidername-YYYYmmdd). Then upload to [Glider Deployment](https://drive.google.com/drive/folders/1qfKMxXH0hUhbmOp8aESidz-YO3IPxWM3?usp=sharing) Google Drive.
- [ ] Download the [GCP folder template](https://drive.google.com/drive/folders/155F-NTGW-GGFyxpiUcZ3pAgqXG6h9vG3?usp=drive_link) and rename it (glidername-YYYYmmdd).
- [ ] Update the [Glider&Mooring Database](\\swc-storage4-s\AMLR_Datasets\Glider Database) with device and glider build information, making sure that the serial numbers are correct. 
- [ ]

**Comment by jgwalsh** [comment]
Glider is ballasted, sealed, checked out, and roll was checked. Need to charge and set m_coulomb_amphr_total to 0.

**Comment by acossio** [comment]
Glider has been resetting itself. Put in a help request with TWR. (CRO-00013181). The glider was coming back with 255 to the request of why_started. Glider support suggested installing 11.01 software on the glider to see if we can get a better understanding of the issue.  Glider aborted for digifin_leakdetect. Then 3 hours into a simulation, the glider reset. It aborted for 18 -Power down/cold boot.  Waiting for a response from glider support. We're building george as the glider to use for this deployment now.

**Comment by acossio** [comment]
Response from Glider support on 9/4/24
CRO-00013181

Jen,

The best guess I can give right now is there is some physical connection issue.  The evidence suggests that there is some momentary connection issue related to power.  

I have seen this before in one of our in-house gliders and was able to narrow it down to the MCBH connector (green plug).  I could cause the "restart" by wiggling the green plug.  This also is supported by the first instance of it restarting was when it was brought outside for the FCP (possibly jostled) and the second time was after 3 hours of simulation (possible vibration of the pump and pitch motor running overtime).

So my best recommendation would be to closely inspect all connections.  Specifically the following:

1.  White connectors between the main tray and science aft.  Check pins on both the male/female sides.
2.  2nd connection starboard side on the aft of the main tray.  This is labeled lithium and connects the green plug to the board.
3.  Wiggle the green plug itself when it is seated and the glider is powered on.  
4.  Check all connections at the BMS.
5.  Check for any loose ground wires.

I wish I had a better solution at this point but this is a gremlin.  

Please keep me updated and let me know if you find/observe anything new.  I will discuss it with all of the engineers to hopefully work this out.
 

Daniel

I'll start a new issue for this.

**Comment by acossio** [comment]
I'm closing this issue since we didn't use this glider for the Santa Barbara deployment but used george instead. The repair of this glider is on a new issue.
