### ISSUE TITLE
Update glider lab member roles

### ISSUE THREAD

**Issue by smwoodman** [us-amlr/glider-lab#38]
Per CR, add: official position description, program

**Comment by acossio** [comment]
I added position descriptions of who I knew. I don't know your job title. He said we don't need program for the people. He also asked for funding line instead which I placed above the people.

**Comment by smwoodman** [comment]
Whoops, just realized this is a duplicate of https://github.com/SWFSC/glider-lab-manual/issues/4

Closing now, will continue over there. Thanks.
