### ISSUE TITLE
Glider team Google email group

### ISSUE THREAD

**Issue by smwoodman** [us-amlr/glider-lab#51]
It would be handy for sharing docs/GCP management to have an up to date glider team Google Group. 

Could update swfsc.aerd-gliders@noaa.gov, but likely will want a new, ESD-specific group.

Sam will ask Heidi/Christian

**Comment by acossio** [comment]
I was thinking about this earlier this week. Either update the list or start a new one. The current list has George and Heidi and Christian. I'm not sure if they all need to be on the list. Maybe just the worker bees, like us. Would be good to ask Heidi/Christian.

**Comment by smwoodman** [comment]
Ticket created: https://apps-st.fisheries.noaa.gov/jirasm/servicedesk/customer/portal/8/SWFSC-1791

**Comment by smwoodman** [comment]
Group created: nmfs.swfsc.esd-gliders@noaa.gov
